version: 2
jobs:
  js-test:
    docker:
      - image: circleci/node:8.9.0

    steps:
      - checkout
      - restore-cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      
      - run : npm install

      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
          - ./node_modules

      - run : npm run test:unit

  php-test:
    docker:
      - image: circleci/php:7.1-node-browsers 
    steps:
      - checkout
      - run: sudo apt update 
      - run: sudo apt-get install php7.3

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: ./vendor/bin/phpunit

workflows:
  version: 2
  test:
    jobs:
      - php-test:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/
      - js-test:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/